name: Build CoreELEC/VDR Matrix Images

# Controls when the workflow will run
on:
  workflow_dispatch:
    branches: [ coreelec-19-VDR, coreelec-20-VDR, 19.4-Matrix-VDR ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: oprypin/find-latest-tag@v1
        with:
            repository:  Zabrimus/CoreELEC
            releases-only: true
            prefix: 'v'
        id: release_version

      - name: Checkout coreelec-19-VDR
        run: |
          git checkout coreelec-19-VDR
          echo "Current Release: ${release_version}"          

      - name: Checkout coreelec-20-VDR
        run: |
          git checkout coreelec-20-VDR
          echo "Current Release: ${release_version}"

      - name: Checkout 19.4-Matrix-VDR
        run: |
          git checkout 19.4-Matrix-VDR
          echo "Current Release: ${release_version}"

      - uses: actions/upload-artifact@v3
        with:
          name: README.md
          path: README.md

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            README.md
            build.sh