name: Build CoreELEC/VDR 19 Images

# Controls when the workflow will run
on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: oprypin/find-latest-tag@v1
        with:
          repository:  Zabrimus/CoreELEC
          releases-only: true
          prefix: 'v'
        id: current_tag

      - name: Prepare build
        run: |
          mkdir -p image-artifacts
          rm -f image-artifacts/*

      - name: Restore sources cache
        run: |
          if [ -d ../build-cache/sources ]; then 
            rm -f sources  
            ln -s ../build-cache/sources sources
          fi

      - name: Build coreelec-19-VDR
        run: |
          ./build-local.sh -e -9
          mv target/CoreELEC-Amlogic-ng.arm-19.5*-Generic.img.gz image-artifacts/CoreELEC-VDR-Amlogic-ng.arm-19.5-${{ steps.current_tag.outputs.tag }}-Generic.img.gz
          mv target/CoreELEC-Amlogic-ng.arm-19.5*-Generic.img.gz.sha256 image-artifacts/CoreELEC-VDR-Amlogic-ng.arm-19.5-${{ steps.current_tag.outputs.tag }}-Generic.img.gz.sha256          
          mv target/CoreELEC-Amlogic-ng.arm-19.5*.tar image-artifacts/CoreELEC-VDR-Amlogic-ng.arm-19.5-${{ steps.current_tag.outputs.tag }}.tar          

      - name: Save sources cache
        run: |
          mkdir -p ../build-cache
          
          if [ ! -d ../build-cache/sources ]; then
            mv sources ../build-cache/sources
          else
            rm sources
          fi

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: image-artifacts/*
          tag: ${{ steps.current_tag.outputs.tag }}
          overwrite: true
          file_glob: true
