name: Build CoreELEC 19, Stage 1, download all

on:
  workflow_dispatch:
    branches: [ 19.4-Matrix-VDR ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'

      - uses: actions/checkout@v2

      - name: Cache sources
        uses: actions/cache@v2
        env:
          cache-name: coreelec-sources-cache-19
        with:
          path: |
            sources
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}

      - name: Install dependencies
        run: |
          sudo apt-get install build-essential git bc gawk xfonts-utils wget zip zstd libparse-yapp-perl gperf lzop unzip patchutils xsltproc cpio libcxxtools-dev libtntnet-dev 
          sudo apt-get clean

      - name: Start download
        run: |
          PROJECT="Amlogic-ce" ARCH="arm" tools/download-tool

      - name: Show free disk space after download
        run: |
          df -h
          ls -la
