name: Build CoreELEC 19, Stage 1, disable Kodi, disable VDR

on:
  workflow_dispatch:
    branches: [ 19.4-Matrix-VDR ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 12288
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'

      - uses: actions/checkout@v2

      - name: Cache packages
        uses: actions/cache@v2
        env:
          cache-name: coreelec-package-cache-19
        with:
          path: |
            build.CoreELEC-Amlogic-ng.arm-19
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}

      - name: Cache sources
        uses: actions/cache@v2
        env:
          cache-name: coreelec-sources-cache-19
        with:
          path: |
            sources
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}

      - name: Install dependencies
        run: |
          sudo apt-get install build-essential git bc gawk xfonts-utils wget zip zstd libparse-yapp-perl gperf lzop unzip patchutils xsltproc cpio libcxxtools-dev libtntnet-dev 
          sudo apt-get clean

      - name: Show installed packages
        run: |
          dpkg -l

      - name: Show free disk space before build
        run: |
          df -h

      - name: Start build
        run: |
          export VDR="no"
          sed -i -e s/MEDIACENTER="kodi"/MEDIACENTER="no"/ distributions/CoreELEC/options
          make

      - name: Show free disk space after build
        run: |
          df -h
          ls -la
